version: "3"

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"

  mariadb:
    image: mariadb
    volumes:
      - ./mysql-conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"