CREATE DATABASE IF NOT EXISTS exam_php;

USE exam_php;

CREATE TABLE user (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, email VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE product (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, description TEXT, price FLOAT NOT NULL
);

CREATE TABLE order (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id INTEGER NOT NULL, product_id INTEGER NOT NULL, FOREIGN KEY (user_id) REFERENCES user (id), FOREIGN KEY (product_id) REFERENCES product (id)
);

ALTER TABLE user ADD CONSTRAINT unique_email UNIQUE (email);

ALTER TABLE user DROP INDEX password;